container:
    image: python:3.5-slim

code_check_task:
    pip_cache:
        folder: ~/.cache/pip
        fingerprint_script: printf "%s" "py3 pylint requests yapf"
        populate_script: python3 -m pip install pylint requests yapf
    yapf_script:
        - python3 -m yapf --style '.style.yapf' -e '*/third_party/*' -rpd buildkit
        - python3 -m yapf --style '.style.yapf' -rpd devutils
    pylint_script:
        - ./devutils/pylint_buildkit.py --hide-fixme
        - ./devutils/pylint_devutils.py --hide-fixme devutils

validate_config_task:
    validate_config_script: ./devutils/validate_config.py

validate_patches_task:
    pip_cache:
        folder: ~/.cache/pip
        fingerprint_script: printf "%s" "py3 requests"
        populate_script: python3 -m pip install requests
    validate_patches_script: ./devutils/validate_patches.py -r
